### ISSUE TITLE
Select subfields in UDT

### ISSUE THREAD

**Issue by albertshift** [datastax/java-driver#307]
This code:
Select select = QueryBuilder.select().column("name.lastname").from("users");
generates statement:
SELECT "name.lastname" FROM users;
that is INVALID for Cassandra 

Valid statement is
SELECT name.lastname FROM users;

In fact, driver adds quotes for each field in the
Utils.joinAndAppendNames
static StringBuilder appendName(String name, StringBuilder sb) {
sb.append('"').append(name).append('"');
}

it is adding quotes in all cases except strange regex "\\w+(?:\\[.+\\])?" with no comments / docs.

Schema is:
	CREATE TYPE fullname(
		firstname text,
		lastname text);
	CREATE TABLE users(
		id uuid,
		name frozen<fullname>,
		PRIMARY KEY(id));

**Comment by albertshift** [comment]
I found workaround 
Select select = QueryBuilder.select().column("\"name\".\"lastname\"").from("users");

but it is not obvious

may be it is better to have:
public abstract SelectionOrAlias column(String... name);
finally with:
Select select = QueryBuilder.select().column("name", "lastname").from("users");

**Comment by avalanche123** [comment]
Please open an issue on the Java driver jira
